In [11]:
"""Class perceptron"""
import numpy as np
import pandas as pd

class Perceptron(object):
    """Implements a perceptron network"""
    def __init__(self, input_size, lr=1, epochs=100):
        self.W = np.zeros(input_size+1)
        # add one for bias
        self.epochs = epochs
        self.lr = lr
    
    def activation_fn(self, x):
        return 1 if x >= 0 else 0
 
    def predict(self, x):
        z = self.W.T.dot(x)
        a = self.activation_fn(z)
        return a
 
    def fit(self, X, d):
        l = []
        for _ in range(self.epochs):
            el,pe = [], []
            for i in range(d.shape[0]):
                x = np.insert(X[i], 0, 1)
                y = self.predict(x)
                e = d[i] - y
                el = np.append(el,e)
                self.W = self.W + self.lr * e * x
                #print("iter:{}\tX:{}\ty':{}\ty:{}\tW:{}\tel:{}".format(_,X[i],y,d[i],self.W,el))
                l.append({'iter': _,'X': list(X[i]),'y': int(d[i]),'y^': y,'W': list(self.W),'el': list(el), 'MAE': None})
            pe = sum([abs(i) for i in el])/len(el) #MeanAbsoluteError
            l.append({'iter': _,'X': None,'y': None,'y^': None,'W': None,'el': None, 'MAE': pe})
            if pe == 0:
                df = pd.DataFrame(l)
                return df
                break

In [12]:
X = np.array([
        [0, 0],
        [0, 1],
        [1, 0],
        [1, 1]
    ])
d = np.array([0, 0, 0, 1])
     
perceptron = Perceptron(input_size=2, lr=1)
df = perceptron.fit(X, d)
print(*perceptron.W)
df[['iter','X','y','y^','W','el', 'MAE']]

-3.0 2.0 1.0

    iter       X    y   y^                 W                      el   MAE
0      0  [0, 0]  0.0  1.0  [-1.0, 0.0, 0.0]                  [-1.0]   NaN
1      0  [0, 1]  0.0  0.0  [-1.0, 0.0, 0.0]             [-1.0, 0.0]   NaN
2      0  [1, 0]  0.0  0.0  [-1.0, 0.0, 0.0]        [-1.0, 0.0, 0.0]   NaN
3      0  [1, 1]  1.0  0.0   [0.0, 1.0, 1.0]   [-1.0, 0.0, 0.0, 1.0]   NaN
4      0    None  NaN  NaN              None                    None  0.50
5      1  [0, 0]  0.0  1.0  [-1.0, 1.0, 1.0]                  [-1.0]   NaN
6      1  [0, 1]  0.0  1.0  [-2.0, 1.0, 0.0]            [-1.0, -1.0]   NaN
7      1  [1, 0]  0.0  0.0  [-2.0, 1.0, 0.0]       [-1.0, -1.0, 0.0]   NaN
8      1  [1, 1]  1.0  0.0  [-1.0, 2.0, 1.0]  [-1.0, -1.0, 0.0, 1.0]   NaN
9      1    None  NaN  NaN              None                    None  0.75
10     2  [0, 0]  0.0  0.0  [-1.0, 2.0, 1.0]                   [0.0]   NaN
11     2  [0, 1]  0.0  1.0  [-2.0, 2.0, 0.0]             [0.0, -1.0]   NaN
12     2  [1, 0]  0.0  1.0  [-3.0, 1.0, 0.0]       [0.0, -1.0, -1.0]   NaN
13     2  [1, 1]  1.0  0.0  [-2.0, 2.0, 1.0]  [0.0, -1.0, -1.0, 1.0]   NaN
14     2    None  NaN  NaN              None                    None  0.75
15     3  [0, 0]  0.0  0.0  [-2.0, 2.0, 1.0]                   [0.0]   NaN
16     3  [0, 1]  0.0  0.0  [-2.0, 2.0, 1.0]              [0.0, 0.0]   NaN
17     3  [1, 0]  0.0  1.0  [-3.0, 1.0, 1.0]        [0.0, 0.0, -1.0]   NaN
18     3  [1, 1]  1.0  0.0  [-2.0, 2.0, 2.0]   [0.0, 0.0, -1.0, 1.0]   NaN
19     3    None  NaN  NaN              None                    None  0.50
20     4  [0, 0]  0.0  0.0  [-2.0, 2.0, 2.0]                   [0.0]   NaN
21     4  [0, 1]  0.0  1.0  [-3.0, 2.0, 1.0]             [0.0, -1.0]   NaN
22     4  [1, 0]  0.0  0.0  [-3.0, 2.0, 1.0]        [0.0, -1.0, 0.0]   NaN
23     4  [1, 1]  1.0  1.0  [-3.0, 2.0, 1.0]   [0.0, -1.0, 0.0, 0.0]   NaN
24     4    None  NaN  NaN              None                    None  0.25
25     5  [0, 0]  0.0  0.0  [-3.0, 2.0, 1.0]                   [0.0]   NaN
26     5  [0, 1]  0.0  0.0  [-3.0, 2.0, 1.0]              [0.0, 0.0]   NaN
27     5  [1, 0]  0.0  0.0  [-3.0, 2.0, 1.0]         [0.0, 0.0, 0.0]   NaN
28     5  [1, 1]  1.0  1.0  [-3.0, 2.0, 1.0]    [0.0, 0.0, 0.0, 0.0]   NaN
29     5    None  NaN  NaN              None                    None  0.00